/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CancelSubscription200Response
 */
export interface CancelSubscription200Response {
    /**
     *
     * @type {boolean}
     * @memberof CancelSubscription200Response
     */
    'success'?: boolean;
    /**
     *
     * @type {string}
     * @memberof CancelSubscription200Response
     */
    'message'?: string;
}
