/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ClassifyCodeGraphDelta200Response
 */
export interface ClassifyCodeGraphDelta200Response {
    /**
     *
     * @type {boolean}
     * @memberof ClassifyCodeGraphDelta200Response
     */
    'fallbackNeeded': boolean;
    /**
     *
     * @type {boolean}
     * @memberof ClassifyCodeGraphDelta200Response
     */
    'manifestApplied': boolean;
    /**
     *
     * @type {string}
     * @memberof ClassifyCodeGraphDelta200Response
     */
    'parserMode': string;
    /**
     *
     * @type {Array<string>}
     * @memberof ClassifyCodeGraphDelta200Response
     */
    'unresolvedFiles': Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof ClassifyCodeGraphDelta200Response
     */
    'unresolvedFunctions': Array<string>;
    /**
     *
     * @type {string}
     * @memberof ClassifyCodeGraphDelta200Response
     */
    'error'?: string;
}
