/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CntType } from './cnt-type';
/**
 *
 * @export
 * @interface CntSubType
 */
export interface CntSubType {
    /**
     *
     * @type {CntType}
     * @memberof CntSubType
     */
    'handledBy'?: CntType;
    /**
     *
     * @type {string}
     * @memberof CntSubType
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof CntSubType
     */
    'description'?: string;
    /**
     *
     * @type {string}
     * @memberof CntSubType
     */
    'uuid'?: string;
}
