/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CntType
 */
export interface CntType {
    /**
     *
     * @type {string}
     * @memberof CntType
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof CntType
     */
    'uuid'?: string;
}
