/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Node } from './node';
import type { Relationship } from './relationship';
/**
 *
 * @export
 * @interface CodeGraphData
 */
export interface CodeGraphData {
    /**
     *
     * @type {Array<Node>}
     * @memberof CodeGraphData
     */
    'nodes'?: Array<Node>;
    /**
     *
     * @type {Array<Relationship>}
     * @memberof CodeGraphData
     */
    'relationships'?: Array<Relationship>;
}
