/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateBillingPortal200Response
 */
export interface CreateBillingPortal200Response {
    /**
     *
     * @type {boolean}
     * @memberof CreateBillingPortal200Response
     */
    'success'?: boolean;
    /**
     * URL to the Stripe billing portal
     * @type {string}
     * @memberof CreateBillingPortal200Response
     */
    'portalUrl'?: string;
    /**
     * Error or status message (used for error responses)
     * @type {string}
     * @memberof CreateBillingPortal200Response
     */
    'message'?: string;
}
