/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface CreateCheckout200Response
 */
export interface CreateCheckout200Response {
    /**
     *
     * @type {boolean}
     * @memberof CreateCheckout200Response
     */
    'success'?: boolean;
    /**
     *
     * @type {string}
     * @memberof CreateCheckout200Response
     */
    'checkoutUrl'?: string;
    /**
     * GitHub user ID of the user
     * @type {string}
     * @memberof CreateCheckout200Response
     */
    'githubUserId'?: string;
    /**
     * Error message (null for success responses)
     * @type {string}
     * @memberof CreateCheckout200Response
     */
    'error'?: string;
}
