/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface EmailExistsResponse
 */
export interface EmailExistsResponse {
    /**
     * Whether the email address already exists in the invite system
     * @type {boolean}
     * @memberof EmailExistsResponse
     */
    'exists': boolean;
    /**
     * Optional message providing additional context
     * @type {string}
     * @memberof EmailExistsResponse
     */
    'message'?: string;
}
