/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ExplainCodeGraphDelta200Response
 */
export interface ExplainCodeGraphDelta200Response {
    /**
     *
     * @type {boolean}
     * @memberof ExplainCodeGraphDelta200Response
     */
    'ok': boolean;
    /**
     *
     * @type {string}
     * @memberof ExplainCodeGraphDelta200Response
     */
    'text'?: string;
    /**
     *
     * @type {object}
     * @memberof ExplainCodeGraphDelta200Response
     */
    'structured'?: object;
    /**
     *
     * @type {string}
     * @memberof ExplainCodeGraphDelta200Response
     */
    'error'?: string;
}
