/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CntSubType } from './cnt-sub-type';
import type { CntType } from './cnt-type';
import type { File1 } from './file1';
/**
 *
 * @export
 * @interface FileExt
 */
export interface FileExt {
    /**
     *
     * @type {Array<CntType>}
     * @memberof FileExt
     */
    'mimes'?: Array<CntType>;
    /**
     *
     * @type {Array<CntSubType>}
     * @memberof FileExt
     */
    'submimes'?: Array<CntSubType>;
    /**
     *
     * @type {File1}
     * @memberof FileExt
     */
    'indentifies'?: File1;
    /**
     *
     * @type {string}
     * @memberof FileExt
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof FileExt
     */
    'description'?: string;
    /**
     *
     * @type {string}
     * @memberof FileExt
     */
    'uuid'?: string;
}
