/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GenerateInviteCodeRequest
 */
export interface GenerateInviteCodeRequest {
    /**
     * Maximum number of users allowed (default: 1)
     * @type {number}
     * @memberof GenerateInviteCodeRequest
     */
    'maxUses'?: number;
    /**
     * Expiry date/time (optional, NULL = no expiry)
     * @type {string}
     * @memberof GenerateInviteCodeRequest
     */
    'expiresAt'?: string;
}
