/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GenerateInviteCodeResponse
 */
export interface GenerateInviteCodeResponse {
    /**
     * Whether the invite code was generated successfully
     * @type {boolean}
     * @memberof GenerateInviteCodeResponse
     */
    'success': boolean;
    /**
     * Success message
     * @type {string}
     * @memberof GenerateInviteCodeResponse
     */
    'message'?: string;
    /**
     * The generated 6-digit invite code
     * @type {string}
     * @memberof GenerateInviteCodeResponse
     */
    'inviteCode': string;
    /**
     * Maximum number of users allowed
     * @type {number}
     * @memberof GenerateInviteCodeResponse
     */
    'maxUses': number;
    /**
     * Current remaining uses
     * @type {number}
     * @memberof GenerateInviteCodeResponse
     */
    'remainingUses': number;
    /**
     * Expiry date/time (null if no expiry)
     * @type {string}
     * @memberof GenerateInviteCodeResponse
     */
    'expiresAt'?: string;
}
