/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GetLeaderboard500Response
 */
export interface GetLeaderboard500Response {
    /**
     *
     * @type {string}
     * @memberof GetLeaderboard500Response
     */
    'error'?: string;
}
