/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GetCurrentUserSubscriptionStatus200Response
 */
export interface GetCurrentUserSubscriptionStatus200Response {
    /**
     *
     * @type {boolean}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'success'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'hasActiveSubscription'?: boolean;
    /**
     *
     * @type {string}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'status'?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'plan'?: string;
    /**
     *
     * @type {boolean}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'requiresSubscription'?: boolean;
    /**
     * GitHub user ID of the current user
     * @type {string}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'githubUserId'?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'stripeCustomerId'?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'stripeSubscriptionId'?: string;
    /**
     *
     * @type {string}
     * @memberof GetCurrentUserSubscriptionStatus200Response
     */
    'error'?: string;
}
