/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 * Request to grant access to a user. GitHub details (name, user ID) are extracted from the authenticated user\'s GitHub OAuth token on the backend. inviteCode is required when access gate is enabled (ENFORCE_INVITE_CODES=true), optional otherwise.
 * @export
 * @interface GrantAccessRequest
 */
export interface GrantAccessRequest {
    /**
     * The 6-digit invite code to use for access. Required when access gate is enabled, optional when disabled.
     * @type {string}
     * @memberof GrantAccessRequest
     */
    'inviteCode'?: string;
    /**
     * User\'s Twitter/X.com username (optional, without @ prefix)
     * @type {string}
     * @memberof GrantAccessRequest
     */
    'twitterUsername'?: string;
    /**
     * Referral code (optional, ABC123 format - 3 uppercase letters + 3 digits)
     * @type {string}
     * @memberof GrantAccessRequest
     */
    'referralCode'?: string;
}
