/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface GrantAccessResponse
 */
export interface GrantAccessResponse {
    /**
     * Whether access was granted successfully
     * @type {boolean}
     * @memberof GrantAccessResponse
     */
    'success': boolean;
    /**
     * Success message
     * @type {string}
     * @memberof GrantAccessResponse
     */
    'message': string;
    /**
     * The user\'s email address
     * @type {string}
     * @memberof GrantAccessResponse
     */
    'email': string;
    /**
     * The invite code that was used (only present when access gate is enabled)
     * @type {string}
     * @memberof GrantAccessResponse
     */
    'inviteCode'?: string;
    /**
     * The PostgreSQL user ID (not github_user_id)
     * @type {string}
     * @memberof GrantAccessResponse
     */
    'userId': string;
    /**
     * The user\'s newly generated referral code
     * @type {string}
     * @memberof GrantAccessResponse
     */
    'referralCode'?: string;
}
