/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface HandleWebhook200Response
 */
export interface HandleWebhook200Response {
    /**
     *
     * @type {boolean}
     * @memberof HandleWebhook200Response
     */
    'success'?: boolean;
    /**
     *
     * @type {string}
     * @memberof HandleWebhook200Response
     */
    'message'?: string;
    /**
     *
     * @type {string}
     * @memberof HandleWebhook200Response
     */
    'eventType'?: string;
    /**
     *
     * @type {string}
     * @memberof HandleWebhook200Response
     */
    'eventId'?: string;
    /**
     * Error message (null for success responses)
     * @type {string}
     * @memberof HandleWebhook200Response
     */
    'error'?: string;
}
