/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @enum {string}
 */
export declare enum HealthStatus {
    AllGood = "ALL_GOOD",
    CodeGraphDown = "CODE_GRAPH_DOWN",
    InfoGraphDown = "INFO_GRAPH_DOWN",
    GraphsDown = "GRAPHS_DOWN",
    RepoRootEmpty = "REPO_ROOT_EMPTY",
    AllDown = "ALL_DOWN",
    RepoNameMismatch = "REPO_NAME_MISMATCH"
}
