/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LeaderboardEntry
 */
export interface LeaderboardEntry {
    /**
     * User\'s display name (default: \'GitHub User\')
     * @type {string}
     * @memberof LeaderboardEntry
     */
    'name'?: string;
    /**
     * User\'s Twitter username (optional)
     * @type {string}
     * @memberof LeaderboardEntry
     */
    'twitterUsername'?: string;
    /**
     * URL to Twitter profile picture (placeholder for now)
     * @type {string}
     * @memberof LeaderboardEntry
     */
    'twitterProfilePicture'?: string;
    /**
     * User\'s rank position in the leaderboard for this month
     * @type {number}
     * @memberof LeaderboardEntry
     */
    'rank'?: number;
    /**
     * Number of users invited by this user
     * @type {number}
     * @memberof LeaderboardEntry
     */
    'usersInvitedCount': number;
    /**
     * When the user was created
     * @type {string}
     * @memberof LeaderboardEntry
     */
    'createdAt'?: string;
}
