/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface Node
 */
export interface Node {
    /**
     *
     * @type {string}
     * @memberof Node
     */
    'id'?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof Node
     */
    'labels'?: Array<string>;
    /**
     *
     * @type {{ [key: string]: object; }}
     * @memberof Node
     */
    'properties'?: {
        [key: string]: object;
    };
}
