/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ReferralCodeValidationResponse
 */
export interface ReferralCodeValidationResponse {
    /**
     * Whether the referral code is valid
     * @type {boolean}
     * @memberof ReferralCodeValidationResponse
     */
    'valid': boolean;
    /**
     * The referral code that was validated
     * @type {string}
     * @memberof ReferralCodeValidationResponse
     */
    'referralCode': string;
}
