/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { RepoStatus } from './repo-status';
/**
 *
 * @export
 * @interface Repo
 */
export interface Repo {
    /**
     *
     * @type {RepoStatus}
     * @memberof Repo
     */
    'status'?: RepoStatus;
    /**
     *
     * @type {Array<any>}
     * @memberof Repo
     */
    'files'?: Array<any>;
    /**
     *
     * @type {string}
     * @memberof Repo
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof Repo
     */
    'lastModifiedDate'?: string;
    /**
     *
     * @type {string}
     * @memberof Repo
     */
    'lastModifiedTime'?: string;
    /**
     *
     * @type {string}
     * @memberof Repo
     */
    'uuid'?: string;
}
