/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateEmailResponse
 */
export interface UpdateEmailResponse {
    /**
     * Whether the email was updated successfully
     * @type {boolean}
     * @memberof UpdateEmailResponse
     */
    'success': boolean;
    /**
     * Success or error message
     * @type {string}
     * @memberof UpdateEmailResponse
     */
    'message': string;
}
