/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateEmailRequest
 */
export interface UpdateEmailRequest {
    /**
     * The PostgreSQL user ID (not github_user_id)
     * @type {string}
     * @memberof UpdateEmailRequest
     */
    'userId': string;
    /**
     * The new email address
     * @type {string}
     * @memberof UpdateEmailRequest
     */
    'email': string;
}
