/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Repo } from './repo';
import type { UserOAuthProvider } from './user-oauth-provider';
/**
 *
 * @export
 * @interface User
 */
export interface User {
    /**
     *
     * @type {Array<Repo>}
     * @memberof User
     */
    'worksWith'?: Array<Repo>;
    /**
     *
     * @type {UserOAuthProvider}
     * @memberof User
     */
    'oAuthProvider'?: UserOAuthProvider;
    /**
     *
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof User
     */
    'uuid'?: string;
}
