/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserAccessStatus
 */
export interface UserAccessStatus {
    /**
     * User\'s email address
     * @type {string}
     * @memberof UserAccessStatus
     */
    'email': string;
    /**
     * Whether the user has access to the system
     * @type {boolean}
     * @memberof UserAccessStatus
     */
    'hasAccess': boolean;
    /**
     * How the user gained access
     * @type {string}
     * @memberof UserAccessStatus
     */
    'accessMethod': UserAccessStatusAccessMethodEnum;
    /**
     * The invite code this user used to join (if any)
     * @type {string}
     * @memberof UserAccessStatus
     */
    'joinedUsingInviteCode'?: string;
    /**
     * Whether the invite/referral system is enabled on the server (from REQUIRE_REFERRAL_SYSTEM environment variable)
     * @type {boolean}
     * @memberof UserAccessStatus
     */
    'inviteSystemEnabled': boolean;
    /**
     * Whether the access code gate is enabled (from ENFORCE_INVITE_CODES environment variable). Only relevant when inviteSystemEnabled is true.
     * @type {boolean}
     * @memberof UserAccessStatus
     */
    'accessGateEnabled': boolean;
}
/**
    * @export
    * @enum {string}
    */
export declare enum UserAccessStatusAccessMethodEnum {
    None = "none",
    Direct = "direct",
    InviteCode = "invite_code"
}
