/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UserInviteInfo
 */
export interface UserInviteInfo {
    /**
     * User\'s email address
     * @type {string}
     * @memberof UserInviteInfo
     */
    'email': string;
    /**
     * User\'s display name from GitHub (default: \'GitHub User\')
     * @type {string}
     * @memberof UserInviteInfo
     */
    'name'?: string;
    /**
     * User\'s unique referral code (ABC123 format - 3 uppercase letters + 3 digits)
     * @type {string}
     * @memberof UserInviteInfo
     */
    'referralCode'?: string;
    /**
     * Whether the user has access to the system
     * @type {boolean}
     * @memberof UserInviteInfo
     */
    'hasAccess': boolean;
    /**
     * Number of users invited by this user
     * @type {number}
     * @memberof UserInviteInfo
     */
    'usersInvitedCount': number;
    /**
     * Number of referral discount months already applied to the referrer
     * @type {number}
     * @memberof UserInviteInfo
     */
    'referralDiscountsAppliedCount'?: number;
    /**
     * The invite code this user used to join (if any)
     * @type {string}
     * @memberof UserInviteInfo
     */
    'joinedUsingInviteCode'?: string;
    /**
     * Type of access code used: \'invite\' (default, invited by another user or registered directly) or \'referral\' (joined via referral code)
     * @type {string}
     * @memberof UserInviteInfo
     */
    'codeType'?: UserInviteInfoCodeTypeEnum;
    /**
     * User\'s Twitter/X.com username (if provided)
     * @type {string}
     * @memberof UserInviteInfo
     */
    'twitterUsername'?: string;
    /**
     * User\'s GitHub user ID
     * @type {string}
     * @memberof UserInviteInfo
     */
    'githubUserId'?: string;
    /**
     * When the user was created
     * @type {string}
     * @memberof UserInviteInfo
     */
    'createdAt'?: string;
    /**
     * When the user was granted access
     * @type {string}
     * @memberof UserInviteInfo
     */
    'accessedAt'?: string;
}
/**
    * @export
    * @enum {string}
    */
export declare enum UserInviteInfoCodeTypeEnum {
    Invite = "invite",
    Referral = "referral"
}
