/**
 * SuperModel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import { type RequestArgs, BaseAPI } from '../base';
import type { AiModelTag } from '../model';
import type { CancelSubscription200Response } from '../model';
import type { CheckEmailExistsRequest } from '../model';
import type { ClassifyCodeGraphDelta200Response } from '../model';
import type { CreateBillingPortal200Response } from '../model';
import type { CreateCheckout200Response } from '../model';
import type { CreateCheckoutRequest } from '../model';
import type { EmailExistsResponse } from '../model';
import type { ExplainCodeGraphDelta200Response } from '../model';
import type { ExplainCodeGraphDeltaRequest } from '../model';
import type { FileExt } from '../model';
import type { GenerateInviteCodeRequest } from '../model';
import type { GenerateInviteCodeResponse } from '../model';
import type { GetCurrentUserSubscriptionStatus200Response } from '../model';
import type { GrantAccessRequest } from '../model';
import type { GrantAccessResponse } from '../model';
import type { HandleWebhook200Response } from '../model';
import type { InviteValidationResponse } from '../model';
import type { LeaderboardEntry } from '../model';
import type { ReferralCodeValidationRequest } from '../model';
import type { ReferralCodeValidationResponse } from '../model';
import type { Repo } from '../model';
import type { UpdateEmailRequest } from '../model';
import type { UpdateEmailResponse } from '../model';
import type { User } from '../model';
import type { UserAccessStatus } from '../model';
import type { UserInviteInfo } from '../model';
import type { UserOAuthProvider } from '../model';
import type { ValidateInviteCodeRequest } from '../model';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export declare const DefaultApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary Cancel a user\'s subscription
     * @param {string} githubUserId GitHub user ID of the user
     * @param {string} stripeSubscriptionId Stripe subscription ID to cancel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelSubscription: (githubUserId: string, stripeSubscriptionId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Check if an email address already exists in the invite system
     * @param {CheckEmailExistsRequest} checkEmailExistsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkEmailExists: (checkEmailExistsRequest: CheckEmailExistsRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Check if the current user has access to the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkUserAccess: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Incrementally reconcile changed files using existing domain assignments when possible.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDeltaParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis when heuristics require a fallback.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    classifyCodeGraphDelta: (repoUuid: string, parserMode?: ClassifyCodeGraphDeltaParserModeEnum, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Step 1 of classification: Analyzes the code and assigns a primary domain.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDomainsParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    classifyCodeGraphDomains: (repoUuid: string, parserMode?: ClassifyCodeGraphDomainsParserModeEnum, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Generates a secure link to Stripe\'s billing portal where users can manage their subscription, update payment methods, view invoices, and cancel subscriptions
     * @summary Create a Stripe billing portal session for subscription management
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBillingPortal: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCallgraph: (repoUuid: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Create a Stripe checkout session for a user to complete payment
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckout: (createCheckoutRequest: CreateCheckoutRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {boolean} [callgraph]
     * @param {CreateCodeGraphParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCodeGraph: (repoUuid: string, callgraph?: boolean, parserMode?: CreateCodeGraphParserModeEnum, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewRepository: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete a node from the graph. Only nodes owned by the user can be deleted.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNode: (repoUuid: string, nodeId: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Delete a repository. Only the repository owner can delete their repositories.
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteRepository: (repoUuid: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Explain recent changes using LLM analysis of graph delta and file stats.
     * @param {string} repoUuid
     * @param {ExplainCodeGraphDeltaRequest} explainCodeGraphDeltaRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    explainCodeGraphDelta: (repoUuid: string, explainCodeGraphDeltaRequest: ExplainCodeGraphDeltaRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Generate a new admin invite code (6 digits). Requires admin credentials in headers.
     * @param {string} xAdminSecretKey Admin secret key (must match SUPERMODEL_GENERATE_INVITE_SECRET_KEY environment variable)
     * @param {string} xAdminApiKey Admin API key (must match SUPERMODEL_GENERATE_INVITE_API_KEY environment variable)
     * @param {GenerateInviteCodeRequest} generateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateInviteCode: (xAdminSecretKey: string, xAdminApiKey: string, generateInviteCodeRequest: GenerateInviteCodeRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCodeGraph: (repoUuid: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {string} elementId
     * @param {boolean} [includeCodeSnippets]
     * @param {number} [maxDepth]
     * @param {boolean} [includeRelatedPatterns]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContext: (repoUuid: string, elementId: string, includeCodeSnippets?: boolean, maxDepth?: number, includeRelatedPatterns?: boolean, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     * Single source of truth endpoint for current user\'s subscription status. Uses GitHub ID from authenticated principal for user identification.
     * @summary Get the current user\'s subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCurrentUserSubscriptionStatus: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileExts: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Liveness probe endpoint. Returns 204 when the process is responsive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthLiveness: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Readiness probe endpoint. Returns 204 when dependencies are ready to serve traffic.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthReadiness: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Startup probe endpoint. Returns 204 when the application has started.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthStartup: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get the leaderboard of users by invite count for the current month
     * @param {number} [limit] Number of users to return in leaderboard (default: 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLeaderboard: (limit?: number, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary The method will return the user associated with the provided Bearer Token based on the provided oAuthProvider. If the user is not registered a 401 will be returned and this new client should post to this endpoint.
     * @param {UserOAuthProvider} [oAuthProvider]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRegistration: (oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary This method will return a complete list of the repositories managed by the code graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositories: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositoryById: (repoUuid: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositoryFiles: (repoUuid: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Get the current user\'s invite information including their invite code and stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserInviteInfo: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Grant access to a user using a valid invite code. User must be authenticated via GitHub OAuth. Email and GitHub details are extracted from the OAuth token.
     * @param {GrantAccessRequest} grantAccessRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    grantAccess: (grantAccessRequest: GrantAccessRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Handle Stripe webhook events (applies pending referral discounts)
     * @param {string} stripeSignature Stripe signature for webhook verification
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleWebhook: (stripeSignature: string, body: string, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary MCP endpoint for the code graph, accepting JSON-RPC 2.0 requests.
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    mcp: (body: object, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary MCP health/info endpoint.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    mcpInfo: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {File} [zippedFiles]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    persistFilesToRepository: (repoUuid: string, zippedFiles?: File, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Returns a Set of file extension details for the provided extension names.
     * @param {Array<string>} fileExtNames The list of file extensions the info graph will described.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processFileExtensions: (fileExtNames: Array<string>, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary
     * @param {Array<string>} fileExtsNames
     * @param {AiModelTag} [aiModelType] The AI model that is intended to be used when the Graph does not contain the answer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processFileExtensionsByModel: (fileExtsNames: Array<string>, aiModelType?: AiModelTag, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary This method will grab the Bearer Token from the HTTP Header and authorize with the OAuth provider specified by the query parameter UserOAuthProvider. Once receiving info from provider and token, store new user in Neo4j and create invite record in PostgreSQL.
     * @param {UserOAuthProvider} [oAuthProvider] OAuth provider (default: GIT_HUB)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerUser: (oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update a user\'s email address in the invite system
     * @param {UpdateEmailRequest} updateEmailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEmail: (updateEmailRequest: UpdateEmailRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Update a node\'s properties. Only nodes owned by the user can be updated.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateNode: (repoUuid: string, nodeId: string, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Validate if an admin invite code (6 digits) is valid and can be used for access
     * @param {ValidateInviteCodeRequest} validateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateInviteCode: (validateInviteCodeRequest: ValidateInviteCodeRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Validate if a referral code is valid (exists in users table)
     * @param {ReferralCodeValidationRequest} referralCodeValidationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateReferralCode: (referralCodeValidationRequest: ReferralCodeValidationRequest, options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * DefaultApi - functional programming interface
 * @export
 */
export declare const DefaultApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary Cancel a user\'s subscription
     * @param {string} githubUserId GitHub user ID of the user
     * @param {string} stripeSubscriptionId Stripe subscription ID to cancel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelSubscription(githubUserId: string, stripeSubscriptionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CancelSubscription200Response>>;
    /**
     *
     * @summary Check if an email address already exists in the invite system
     * @param {CheckEmailExistsRequest} checkEmailExistsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkEmailExists(checkEmailExistsRequest: CheckEmailExistsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmailExistsResponse>>;
    /**
     *
     * @summary Check if the current user has access to the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkUserAccess(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserAccessStatus>>;
    /**
     *
     * @summary Incrementally reconcile changed files using existing domain assignments when possible.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDeltaParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis when heuristics require a fallback.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    classifyCodeGraphDelta(repoUuid: string, parserMode?: ClassifyCodeGraphDeltaParserModeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ClassifyCodeGraphDelta200Response>>;
    /**
     *
     * @summary Step 1 of classification: Analyzes the code and assigns a primary domain.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDomainsParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    classifyCodeGraphDomains(repoUuid: string, parserMode?: ClassifyCodeGraphDomainsParserModeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     * Generates a secure link to Stripe\'s billing portal where users can manage their subscription, update payment methods, view invoices, and cancel subscriptions
     * @summary Create a Stripe billing portal session for subscription management
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBillingPortal(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateBillingPortal200Response>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCallgraph(repoUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     *
     * @summary Create a Stripe checkout session for a user to complete payment
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckout(createCheckoutRequest: CreateCheckoutRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateCheckout200Response>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {boolean} [callgraph]
     * @param {CreateCodeGraphParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCodeGraph(repoUuid: string, callgraph?: boolean, parserMode?: CreateCodeGraphParserModeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewRepository(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Repo>>;
    /**
     *
     * @summary Delete a node from the graph. Only nodes owned by the user can be deleted.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNode(repoUuid: string, nodeId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     *
     * @summary Delete a repository. Only the repository owner can delete their repositories.
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteRepository(repoUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     *
     * @summary Explain recent changes using LLM analysis of graph delta and file stats.
     * @param {string} repoUuid
     * @param {ExplainCodeGraphDeltaRequest} explainCodeGraphDeltaRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    explainCodeGraphDelta(repoUuid: string, explainCodeGraphDeltaRequest: ExplainCodeGraphDeltaRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ExplainCodeGraphDelta200Response>>;
    /**
     *
     * @summary Generate a new admin invite code (6 digits). Requires admin credentials in headers.
     * @param {string} xAdminSecretKey Admin secret key (must match SUPERMODEL_GENERATE_INVITE_SECRET_KEY environment variable)
     * @param {string} xAdminApiKey Admin API key (must match SUPERMODEL_GENERATE_INVITE_API_KEY environment variable)
     * @param {GenerateInviteCodeRequest} generateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateInviteCode(xAdminSecretKey: string, xAdminApiKey: string, generateInviteCodeRequest: GenerateInviteCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GenerateInviteCodeResponse>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCodeGraph(repoUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {string} elementId
     * @param {boolean} [includeCodeSnippets]
     * @param {number} [maxDepth]
     * @param {boolean} [includeRelatedPatterns]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContext(repoUuid: string, elementId: string, includeCodeSnippets?: boolean, maxDepth?: number, includeRelatedPatterns?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     * Single source of truth endpoint for current user\'s subscription status. Uses GitHub ID from authenticated principal for user identification.
     * @summary Get the current user\'s subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCurrentUserSubscriptionStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetCurrentUserSubscriptionStatus200Response>>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileExts(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FileExt>>>;
    /**
     *
     * @summary Liveness probe endpoint. Returns 204 when the process is responsive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthLiveness(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Readiness probe endpoint. Returns 204 when dependencies are ready to serve traffic.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthReadiness(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Startup probe endpoint. Returns 204 when the application has started.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthStartup(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
    /**
     *
     * @summary Get the leaderboard of users by invite count for the current month
     * @param {number} [limit] Number of users to return in leaderboard (default: 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLeaderboard(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<LeaderboardEntry>>>;
    /**
     *
     * @summary The method will return the user associated with the provided Bearer Token based on the provided oAuthProvider. If the user is not registered a 401 will be returned and this new client should post to this endpoint.
     * @param {UserOAuthProvider} [oAuthProvider]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRegistration(oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>>;
    /**
     *
     * @summary This method will return a complete list of the repositories managed by the code graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositories(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Repo>>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositoryById(repoUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Repo>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositoryFiles(repoUuid: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<any>>>;
    /**
     *
     * @summary Get the current user\'s invite information including their invite code and stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserInviteInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserInviteInfo>>;
    /**
     *
     * @summary Grant access to a user using a valid invite code. User must be authenticated via GitHub OAuth. Email and GitHub details are extracted from the OAuth token.
     * @param {GrantAccessRequest} grantAccessRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    grantAccess(grantAccessRequest: GrantAccessRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GrantAccessResponse>>;
    /**
     *
     * @summary Handle Stripe webhook events (applies pending referral discounts)
     * @param {string} stripeSignature Stripe signature for webhook verification
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleWebhook(stripeSignature: string, body: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HandleWebhook200Response>>;
    /**
     *
     * @summary MCP endpoint for the code graph, accepting JSON-RPC 2.0 requests.
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    mcp(body: object, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary MCP health/info endpoint.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    mcpInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {File} [zippedFiles]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    persistFilesToRepository(repoUuid: string, zippedFiles?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Repo>>;
    /**
     *
     * @summary Returns a Set of file extension details for the provided extension names.
     * @param {Array<string>} fileExtNames The list of file extensions the info graph will described.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processFileExtensions(fileExtNames: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FileExt>>>;
    /**
     *
     * @summary
     * @param {Array<string>} fileExtsNames
     * @param {AiModelTag} [aiModelType] The AI model that is intended to be used when the Graph does not contain the answer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processFileExtensionsByModel(fileExtsNames: Array<string>, aiModelType?: AiModelTag, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FileExt>>>;
    /**
     *
     * @summary This method will grab the Bearer Token from the HTTP Header and authorize with the OAuth provider specified by the query parameter UserOAuthProvider. Once receiving info from provider and token, store new user in Neo4j and create invite record in PostgreSQL.
     * @param {UserOAuthProvider} [oAuthProvider] OAuth provider (default: GIT_HUB)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerUser(oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>>;
    /**
     *
     * @summary Update a user\'s email address in the invite system
     * @param {UpdateEmailRequest} updateEmailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEmail(updateEmailRequest: UpdateEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UpdateEmailResponse>>;
    /**
     *
     * @summary Update a node\'s properties. Only nodes owned by the user can be updated.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateNode(repoUuid: string, nodeId: string, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>>;
    /**
     *
     * @summary Validate if an admin invite code (6 digits) is valid and can be used for access
     * @param {ValidateInviteCodeRequest} validateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateInviteCode(validateInviteCodeRequest: ValidateInviteCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InviteValidationResponse>>;
    /**
     *
     * @summary Validate if a referral code is valid (exists in users table)
     * @param {ReferralCodeValidationRequest} referralCodeValidationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateReferralCode(referralCodeValidationRequest: ReferralCodeValidationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReferralCodeValidationResponse>>;
};
/**
 * DefaultApi - factory interface
 * @export
 */
export declare const DefaultApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary Cancel a user\'s subscription
     * @param {string} githubUserId GitHub user ID of the user
     * @param {string} stripeSubscriptionId Stripe subscription ID to cancel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    cancelSubscription(githubUserId: string, stripeSubscriptionId: string, options?: RawAxiosRequestConfig): AxiosPromise<CancelSubscription200Response>;
    /**
     *
     * @summary Check if an email address already exists in the invite system
     * @param {CheckEmailExistsRequest} checkEmailExistsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkEmailExists(checkEmailExistsRequest: CheckEmailExistsRequest, options?: RawAxiosRequestConfig): AxiosPromise<EmailExistsResponse>;
    /**
     *
     * @summary Check if the current user has access to the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkUserAccess(options?: RawAxiosRequestConfig): AxiosPromise<UserAccessStatus>;
    /**
     *
     * @summary Incrementally reconcile changed files using existing domain assignments when possible.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDeltaParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis when heuristics require a fallback.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    classifyCodeGraphDelta(repoUuid: string, parserMode?: ClassifyCodeGraphDeltaParserModeEnum, options?: RawAxiosRequestConfig): AxiosPromise<ClassifyCodeGraphDelta200Response>;
    /**
     *
     * @summary Step 1 of classification: Analyzes the code and assigns a primary domain.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDomainsParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    classifyCodeGraphDomains(repoUuid: string, parserMode?: ClassifyCodeGraphDomainsParserModeEnum, options?: RawAxiosRequestConfig): AxiosPromise<string>;
    /**
     * Generates a secure link to Stripe\'s billing portal where users can manage their subscription, update payment methods, view invoices, and cancel subscriptions
     * @summary Create a Stripe billing portal session for subscription management
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBillingPortal(options?: RawAxiosRequestConfig): AxiosPromise<CreateBillingPortal200Response>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCallgraph(repoUuid: string, options?: RawAxiosRequestConfig): AxiosPromise<string>;
    /**
     *
     * @summary Create a Stripe checkout session for a user to complete payment
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCheckout(createCheckoutRequest: CreateCheckoutRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateCheckout200Response>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {boolean} [callgraph]
     * @param {CreateCodeGraphParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCodeGraph(repoUuid: string, callgraph?: boolean, parserMode?: CreateCodeGraphParserModeEnum, options?: RawAxiosRequestConfig): AxiosPromise<string>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewRepository(options?: RawAxiosRequestConfig): AxiosPromise<Repo>;
    /**
     *
     * @summary Delete a node from the graph. Only nodes owned by the user can be deleted.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNode(repoUuid: string, nodeId: string, options?: RawAxiosRequestConfig): AxiosPromise<string>;
    /**
     *
     * @summary Delete a repository. Only the repository owner can delete their repositories.
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteRepository(repoUuid: string, options?: RawAxiosRequestConfig): AxiosPromise<string>;
    /**
     *
     * @summary Explain recent changes using LLM analysis of graph delta and file stats.
     * @param {string} repoUuid
     * @param {ExplainCodeGraphDeltaRequest} explainCodeGraphDeltaRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    explainCodeGraphDelta(repoUuid: string, explainCodeGraphDeltaRequest: ExplainCodeGraphDeltaRequest, options?: RawAxiosRequestConfig): AxiosPromise<ExplainCodeGraphDelta200Response>;
    /**
     *
     * @summary Generate a new admin invite code (6 digits). Requires admin credentials in headers.
     * @param {string} xAdminSecretKey Admin secret key (must match SUPERMODEL_GENERATE_INVITE_SECRET_KEY environment variable)
     * @param {string} xAdminApiKey Admin API key (must match SUPERMODEL_GENERATE_INVITE_API_KEY environment variable)
     * @param {GenerateInviteCodeRequest} generateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    generateInviteCode(xAdminSecretKey: string, xAdminApiKey: string, generateInviteCodeRequest: GenerateInviteCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<GenerateInviteCodeResponse>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCodeGraph(repoUuid: string, options?: RawAxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {string} elementId
     * @param {boolean} [includeCodeSnippets]
     * @param {number} [maxDepth]
     * @param {boolean} [includeRelatedPatterns]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getContext(repoUuid: string, elementId: string, includeCodeSnippets?: boolean, maxDepth?: number, includeRelatedPatterns?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<object>;
    /**
     * Single source of truth endpoint for current user\'s subscription status. Uses GitHub ID from authenticated principal for user identification.
     * @summary Get the current user\'s subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getCurrentUserSubscriptionStatus(options?: RawAxiosRequestConfig): AxiosPromise<GetCurrentUserSubscriptionStatus200Response>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getFileExts(options?: RawAxiosRequestConfig): AxiosPromise<Array<FileExt>>;
    /**
     *
     * @summary Liveness probe endpoint. Returns 204 when the process is responsive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthLiveness(options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Readiness probe endpoint. Returns 204 when dependencies are ready to serve traffic.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthReadiness(options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Startup probe endpoint. Returns 204 when the application has started.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getHealthStartup(options?: RawAxiosRequestConfig): AxiosPromise<void>;
    /**
     *
     * @summary Get the leaderboard of users by invite count for the current month
     * @param {number} [limit] Number of users to return in leaderboard (default: 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getLeaderboard(limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<LeaderboardEntry>>;
    /**
     *
     * @summary The method will return the user associated with the provided Bearer Token based on the provided oAuthProvider. If the user is not registered a 401 will be returned and this new client should post to this endpoint.
     * @param {UserOAuthProvider} [oAuthProvider]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRegistration(oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig): AxiosPromise<User>;
    /**
     *
     * @summary This method will return a complete list of the repositories managed by the code graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositories(options?: RawAxiosRequestConfig): AxiosPromise<Array<Repo>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositoryById(repoUuid: string, options?: RawAxiosRequestConfig): AxiosPromise<Repo>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getRepositoryFiles(repoUuid: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<any>>;
    /**
     *
     * @summary Get the current user\'s invite information including their invite code and stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserInviteInfo(options?: RawAxiosRequestConfig): AxiosPromise<UserInviteInfo>;
    /**
     *
     * @summary Grant access to a user using a valid invite code. User must be authenticated via GitHub OAuth. Email and GitHub details are extracted from the OAuth token.
     * @param {GrantAccessRequest} grantAccessRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    grantAccess(grantAccessRequest: GrantAccessRequest, options?: RawAxiosRequestConfig): AxiosPromise<GrantAccessResponse>;
    /**
     *
     * @summary Handle Stripe webhook events (applies pending referral discounts)
     * @param {string} stripeSignature Stripe signature for webhook verification
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    handleWebhook(stripeSignature: string, body: string, options?: RawAxiosRequestConfig): AxiosPromise<HandleWebhook200Response>;
    /**
     *
     * @summary MCP endpoint for the code graph, accepting JSON-RPC 2.0 requests.
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    mcp(body: object, options?: RawAxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary MCP health/info endpoint.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    mcpInfo(options?: RawAxiosRequestConfig): AxiosPromise<object>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {File} [zippedFiles]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    persistFilesToRepository(repoUuid: string, zippedFiles?: File, options?: RawAxiosRequestConfig): AxiosPromise<Repo>;
    /**
     *
     * @summary Returns a Set of file extension details for the provided extension names.
     * @param {Array<string>} fileExtNames The list of file extensions the info graph will described.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processFileExtensions(fileExtNames: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<Array<FileExt>>;
    /**
     *
     * @summary
     * @param {Array<string>} fileExtsNames
     * @param {AiModelTag} [aiModelType] The AI model that is intended to be used when the Graph does not contain the answer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    processFileExtensionsByModel(fileExtsNames: Array<string>, aiModelType?: AiModelTag, options?: RawAxiosRequestConfig): AxiosPromise<Array<FileExt>>;
    /**
     *
     * @summary This method will grab the Bearer Token from the HTTP Header and authorize with the OAuth provider specified by the query parameter UserOAuthProvider. Once receiving info from provider and token, store new user in Neo4j and create invite record in PostgreSQL.
     * @param {UserOAuthProvider} [oAuthProvider] OAuth provider (default: GIT_HUB)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    registerUser(oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig): AxiosPromise<User>;
    /**
     *
     * @summary Update a user\'s email address in the invite system
     * @param {UpdateEmailRequest} updateEmailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateEmail(updateEmailRequest: UpdateEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<UpdateEmailResponse>;
    /**
     *
     * @summary Update a node\'s properties. Only nodes owned by the user can be updated.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateNode(repoUuid: string, nodeId: string, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig): AxiosPromise<string>;
    /**
     *
     * @summary Validate if an admin invite code (6 digits) is valid and can be used for access
     * @param {ValidateInviteCodeRequest} validateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateInviteCode(validateInviteCodeRequest: ValidateInviteCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<InviteValidationResponse>;
    /**
     *
     * @summary Validate if a referral code is valid (exists in users table)
     * @param {ReferralCodeValidationRequest} referralCodeValidationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    validateReferralCode(referralCodeValidationRequest: ReferralCodeValidationRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReferralCodeValidationResponse>;
};
/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export declare class DefaultApi extends BaseAPI {
    /**
     *
     * @summary Cancel a user\'s subscription
     * @param {string} githubUserId GitHub user ID of the user
     * @param {string} stripeSubscriptionId Stripe subscription ID to cancel
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    cancelSubscription(githubUserId: string, stripeSubscriptionId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CancelSubscription200Response, any, {}>>;
    /**
     *
     * @summary Check if an email address already exists in the invite system
     * @param {CheckEmailExistsRequest} checkEmailExistsRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    checkEmailExists(checkEmailExistsRequest: CheckEmailExistsRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<EmailExistsResponse, any, {}>>;
    /**
     *
     * @summary Check if the current user has access to the system
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    checkUserAccess(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<UserAccessStatus, any, {}>>;
    /**
     *
     * @summary Incrementally reconcile changed files using existing domain assignments when possible.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDeltaParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis when heuristics require a fallback.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    classifyCodeGraphDelta(repoUuid: string, parserMode?: ClassifyCodeGraphDeltaParserModeEnum, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<ClassifyCodeGraphDelta200Response, any, {}>>;
    /**
     *
     * @summary Step 1 of classification: Analyzes the code and assigns a primary domain.
     * @param {string} repoUuid
     * @param {ClassifyCodeGraphDomainsParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    classifyCodeGraphDomains(repoUuid: string, parserMode?: ClassifyCodeGraphDomainsParserModeEnum, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any, {}>>;
    /**
     * Generates a secure link to Stripe\'s billing portal where users can manage their subscription, update payment methods, view invoices, and cancel subscriptions
     * @summary Create a Stripe billing portal session for subscription management
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createBillingPortal(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CreateBillingPortal200Response, any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createCallgraph(repoUuid: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any, {}>>;
    /**
     *
     * @summary Create a Stripe checkout session for a user to complete payment
     * @param {CreateCheckoutRequest} createCheckoutRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createCheckout(createCheckoutRequest: CreateCheckoutRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<CreateCheckout200Response, any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {boolean} [callgraph]
     * @param {CreateCodeGraphParserModeEnum} [parserMode] Specifies the parser mode to use for code analysis. Options: tree-sitter (recommended), or grep (basic text parsing).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createCodeGraph(repoUuid: string, callgraph?: boolean, parserMode?: CreateCodeGraphParserModeEnum, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any, {}>>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    createNewRepository(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Repo, any, {}>>;
    /**
     *
     * @summary Delete a node from the graph. Only nodes owned by the user can be deleted.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    deleteNode(repoUuid: string, nodeId: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any, {}>>;
    /**
     *
     * @summary Delete a repository. Only the repository owner can delete their repositories.
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    deleteRepository(repoUuid: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any, {}>>;
    /**
     *
     * @summary Explain recent changes using LLM analysis of graph delta and file stats.
     * @param {string} repoUuid
     * @param {ExplainCodeGraphDeltaRequest} explainCodeGraphDeltaRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    explainCodeGraphDelta(repoUuid: string, explainCodeGraphDeltaRequest: ExplainCodeGraphDeltaRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<ExplainCodeGraphDelta200Response, any, {}>>;
    /**
     *
     * @summary Generate a new admin invite code (6 digits). Requires admin credentials in headers.
     * @param {string} xAdminSecretKey Admin secret key (must match SUPERMODEL_GENERATE_INVITE_SECRET_KEY environment variable)
     * @param {string} xAdminApiKey Admin API key (must match SUPERMODEL_GENERATE_INVITE_API_KEY environment variable)
     * @param {GenerateInviteCodeRequest} generateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    generateInviteCode(xAdminSecretKey: string, xAdminApiKey: string, generateInviteCodeRequest: GenerateInviteCodeRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<GenerateInviteCodeResponse, any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCodeGraph(repoUuid: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {string} elementId
     * @param {boolean} [includeCodeSnippets]
     * @param {number} [maxDepth]
     * @param {boolean} [includeRelatedPatterns]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getContext(repoUuid: string, elementId: string, includeCodeSnippets?: boolean, maxDepth?: number, includeRelatedPatterns?: boolean, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any, {}>>;
    /**
     * Single source of truth endpoint for current user\'s subscription status. Uses GitHub ID from authenticated principal for user identification.
     * @summary Get the current user\'s subscription status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getCurrentUserSubscriptionStatus(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<GetCurrentUserSubscriptionStatus200Response, any, {}>>;
    /**
     *
     * @summary
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getFileExts(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<FileExt[], any, {}>>;
    /**
     *
     * @summary Liveness probe endpoint. Returns 204 when the process is responsive.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getHealthLiveness(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Readiness probe endpoint. Returns 204 when dependencies are ready to serve traffic.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getHealthReadiness(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Startup probe endpoint. Returns 204 when the application has started.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getHealthStartup(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<void, any, {}>>;
    /**
     *
     * @summary Get the leaderboard of users by invite count for the current month
     * @param {number} [limit] Number of users to return in leaderboard (default: 10)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getLeaderboard(limit?: number, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<LeaderboardEntry[], any, {}>>;
    /**
     *
     * @summary The method will return the user associated with the provided Bearer Token based on the provided oAuthProvider. If the user is not registered a 401 will be returned and this new client should post to this endpoint.
     * @param {UserOAuthProvider} [oAuthProvider]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getRegistration(oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<User, any, {}>>;
    /**
     *
     * @summary This method will return a complete list of the repositories managed by the code graph.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getRepositories(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Repo[], any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getRepositoryById(repoUuid: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Repo, any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getRepositoryFiles(repoUuid: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<any[], any, {}>>;
    /**
     *
     * @summary Get the current user\'s invite information including their invite code and stats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    getUserInviteInfo(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<UserInviteInfo, any, {}>>;
    /**
     *
     * @summary Grant access to a user using a valid invite code. User must be authenticated via GitHub OAuth. Email and GitHub details are extracted from the OAuth token.
     * @param {GrantAccessRequest} grantAccessRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    grantAccess(grantAccessRequest: GrantAccessRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<GrantAccessResponse, any, {}>>;
    /**
     *
     * @summary Handle Stripe webhook events (applies pending referral discounts)
     * @param {string} stripeSignature Stripe signature for webhook verification
     * @param {string} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    handleWebhook(stripeSignature: string, body: string, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<HandleWebhook200Response, any, {}>>;
    /**
     *
     * @summary MCP endpoint for the code graph, accepting JSON-RPC 2.0 requests.
     * @param {object} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    mcp(body: object, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any, {}>>;
    /**
     *
     * @summary MCP health/info endpoint.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    mcpInfo(options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<object, any, {}>>;
    /**
     *
     * @summary
     * @param {string} repoUuid
     * @param {File} [zippedFiles]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    persistFilesToRepository(repoUuid: string, zippedFiles?: File, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<Repo, any, {}>>;
    /**
     *
     * @summary Returns a Set of file extension details for the provided extension names.
     * @param {Array<string>} fileExtNames The list of file extensions the info graph will described.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    processFileExtensions(fileExtNames: Array<string>, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<FileExt[], any, {}>>;
    /**
     *
     * @summary
     * @param {Array<string>} fileExtsNames
     * @param {AiModelTag} [aiModelType] The AI model that is intended to be used when the Graph does not contain the answer
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    processFileExtensionsByModel(fileExtsNames: Array<string>, aiModelType?: AiModelTag, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<FileExt[], any, {}>>;
    /**
     *
     * @summary This method will grab the Bearer Token from the HTTP Header and authorize with the OAuth provider specified by the query parameter UserOAuthProvider. Once receiving info from provider and token, store new user in Neo4j and create invite record in PostgreSQL.
     * @param {UserOAuthProvider} [oAuthProvider] OAuth provider (default: GIT_HUB)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    registerUser(oAuthProvider?: UserOAuthProvider, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<User, any, {}>>;
    /**
     *
     * @summary Update a user\'s email address in the invite system
     * @param {UpdateEmailRequest} updateEmailRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    updateEmail(updateEmailRequest: UpdateEmailRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<UpdateEmailResponse, any, {}>>;
    /**
     *
     * @summary Update a node\'s properties. Only nodes owned by the user can be updated.
     * @param {string} repoUuid
     * @param {string} nodeId
     * @param {{ [key: string]: any; }} requestBody
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    updateNode(repoUuid: string, nodeId: string, requestBody: {
        [key: string]: any;
    }, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<string, any, {}>>;
    /**
     *
     * @summary Validate if an admin invite code (6 digits) is valid and can be used for access
     * @param {ValidateInviteCodeRequest} validateInviteCodeRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    validateInviteCode(validateInviteCodeRequest: ValidateInviteCodeRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<InviteValidationResponse, any, {}>>;
    /**
     *
     * @summary Validate if a referral code is valid (exists in users table)
     * @param {ReferralCodeValidationRequest} referralCodeValidationRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    validateReferralCode(referralCodeValidationRequest: ReferralCodeValidationRequest, options?: RawAxiosRequestConfig): Promise<import("axios").AxiosResponse<ReferralCodeValidationResponse, any, {}>>;
}
/**
  * @export
  * @enum {string}
  */
export declare enum ClassifyCodeGraphDeltaParserModeEnum {
    TreeSitter = "tree-sitter",
    Grep = "grep"
}
/**
  * @export
  * @enum {string}
  */
export declare enum ClassifyCodeGraphDomainsParserModeEnum {
    TreeSitter = "tree-sitter",
    Grep = "grep"
}
/**
  * @export
  * @enum {string}
  */
export declare enum CreateCodeGraphParserModeEnum {
    TreeSitter = "tree-sitter",
    Grep = "grep"
}
